import { StyleSheet, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
const BANNER_HEIGHT = Math.round(SCREEN_WIDTH * 0.45);

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f7f7f7' },
  gregorian: { color: '#fff', fontSize: 16, marginTop: 2 },
  searchBar: {
    backgroundColor: '#fff',
    borderRadius: 22,
    width: '88%',
    marginBottom: 0,
    paddingHorizontal: 18,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 2,
  },
  searchPlaceholder: {
    color: '#bbb',
    fontSize: 16,
  },
  searchBarOverlapWrapper: {
    position: 'absolute',
    top: BANNER_HEIGHT - 28,
    left: 0,
    width: '100%',
    alignItems: 'center',
    zIndex: 2,
  },
  ayatCard: {
    backgroundColor: '#fff',
    margin: 18,
    marginTop: 36,
    borderRadius: 16,
    padding: 18,
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 4,
    alignItems: 'flex-end',
  },
  ayatArabic: {
    fontSize: 22,
    color: '#222',
    textAlign: 'right',
    fontFamily: 'System',
    marginBottom: 8,
  },
  ayatSurah: { fontSize: 14, color: '#888', textAlign: 'right' },
  promoCard: {
    backgroundColor: '#eaf2fa',
    marginHorizontal: 16,
    borderRadius: 16,
    padding: 18,
    marginTop: 8,
    alignItems: 'center',
  },
  promoTitle: {
    color: '#d32f2f',
    fontWeight: 'bold',
    fontSize: 18,
    marginBottom: 6,
  },
  promoText: { color: '#222', fontSize: 16, textAlign: 'center' },
  quranButton: {
    backgroundColor: '#4B3F2F', // or your preferred color
    paddingHorizontal: 32,
    paddingVertical: 14,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    width: '90%',
  },
  quranButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 20,
    letterSpacing: 1,
  },
  bannerWrapper: {
    height: BANNER_HEIGHT,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  bannerImage: {
    ...StyleSheet.absoluteFillObject,
    width: SCREEN_WIDTH,
    height: BANNER_HEIGHT,
  },
  bannerDateOverlay: {
    position: 'absolute',
    left: 24,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    zIndex: 2,
  },
  bannerDateText: {
    color: '#fff',
    fontSize: 28,
    fontWeight: 'bold',
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 4,
    letterSpacing: 1,
  },
  bannerDateSub: {
    color: '#f0f0f0',
    fontSize: 16,
    fontWeight: '400',
    textShadowColor: 'rgba(0,0,0,0.4)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
    marginTop: 2,
    letterSpacing: 0.5,
  },
});

export default styles;
