// pages/ReadQuranScreen/ReadQuranScreen.style.ts
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  tabContainer: { flexDirection: 'row', marginBottom: 12, marginTop: 8 },
  tab: {
    flex: 1,
    paddingVertical: 10,
    backgroundColor: '#eee',
    alignItems: 'center',
    borderRadius: 8,
    marginHorizontal: 4,
  },
  tabActive: { backgroundColor: '#007bff' },
  tabText: { color: '#333', fontWeight: 'bold' },
  tabTextActive: { color: '#fff' },
  tabItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    position: 'relative',
    paddingVertical: 10,
  },
  tabIndicator: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 0,
    height: 3,
    backgroundColor: '#4b3b2a',
    borderRadius: 2,
  },
  juzCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginHorizontal: 12,
    marginTop: 8,
    marginBottom: 0,
    paddingVertical: 8,
    paddingHorizontal: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
    elevation: 1,
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 48,
  },
  juzRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
  },
  juzMedal: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#e0e0e0',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
    marginRight: 0,
  },
  juzMedalText: {
    color: '#000',
    fontWeight: 'bold',
    fontSize: 12,
  },
  juzTitleAr: {
    color: '#222',
    fontWeight: 'bold',
    fontSize: 18,
    marginRight: 8,
    marginLeft: 8,
    textAlign: 'right',
    fontFamily: 'QCF_BSML',
    flex: 0,
    minWidth: 50,
  },
  juzTitleEn: {
    color: '#222',
    fontWeight: 'bold',
    fontSize: 14,
    marginBottom: 0,
  },
  surahCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginHorizontal: 12,
    marginTop: 8,
    marginBottom: 0,
    paddingVertical: 8,
    paddingHorizontal: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
    elevation: 1,
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 48,
  },
  surahRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
  },
  surahMedal: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#e0e0e0',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
    marginRight: 0,
  },
  surahMedalText: {
    color: '#000',
    fontWeight: 'bold',
    fontSize: 12,
  },
  surahTitleAr: {
    color: '#222',
    fontWeight: 'bold',
    fontSize: 18,
    marginRight: 8,
    marginLeft: 8,
    textAlign: 'right',
    fontFamily: 'QCF_BSML',
    flex: 0,
    minWidth: 50,
  },
  surahTitleEn: {
    color: '#222',
    fontWeight: 'bold',
    fontSize: 14,
    marginBottom: 0,
  },
  resumeButtonContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255,255,255,0.95)',
    padding: 18,
    alignItems: 'center',
    borderTopWidth: 1,
    borderColor: '#eee',
    zIndex: 10,
  },
  resumeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#4b3b2a',
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 24,
    minWidth: 260,
    width: '90%',
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  resumeLogo: {
    width: 28,
    height: 28,
    marginRight: 10,
    borderRadius: 14,
    backgroundColor: '#fff',
  },
  resumeArrow:{
    width: 28,
    height: 28,
  },
  resumeButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 20,
    letterSpacing: 0.5,
  },
  fab: {
    position: 'absolute',
    right: 24,
    bottom: 100, // Resume Reading button se upar
    backgroundColor: '#4b3b2a',
    borderRadius: 28,
    width: 56,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    zIndex:1
  },
  fabIcon: {
    width: 32,
    height: 32,
    resizeMode: 'contain',
    tintColor: '#fff', // Add this line
  },
});

export default styles;
